### ISSUE TITLE
When the `show_numbers` option is set, the files can't be seen

### ISSUE THREAD

**Issue by tmwatchanan** [dedukun/relative-motions.yazi#1] opened 2024-02-24 18:04 UTC
# Description
Hey @dedukun, thanks for your this wonderful plugin!

I'm using yazi 0.2.3 (at the HEAD). It seems to work with number + commands. But the problem is that I couldn't see any files besides the preview file list in the right-most section (see the screenshot below). Can you please help me figure out what's the problem here?

# Screenshot
![image](https://github.com/dedukun/relative-motions.yazi/assets/13808339/95a1944e-5186-41ab-adb9-00091b6e32a0)

# My `~/.config/yazi/init.lua`
```lua
require('relative-motions'):setup({
    show_numbers = 'relative_absolute',
    show_motion = true,
})
```

**Comment by dedukun** [comment] 2024-02-24 18:20
Hey, it seems that the last commit in yazi changed the code that we are using for the render of the numbers (talk about timing... :sweat_smile:).

I'll look into the new render code and update the plugin accordingly.

**Comment by tmwatchanan** [comment] 2024-02-24 18:22
Oh I see. Thanks for your prompt response. I'll try again once you're done with the update.

**Comment by tmwatchanan** [comment] 2024-02-24 18:58
It works perfectly now! Thanks so much @dedukun.

BTW, it'd be good if the absolute line number gets a distinct look compared to the other relative line numbers.

![image](https://github.com/dedukun/relative-motions.yazi/assets/13808339/a281acdc-df0f-4af6-8c5d-0edeb97ad78b)

**Comment by dedukun** [comment] 2024-02-24 19:19
What do you think would be a good look? Maybe I'll add a way for the user to configure via the `setup` function how they want the numbers to look.

**Comment by dedukun** [comment] 2024-02-24 21:31
Do you mind testing #3? If that's works as expected I'll merge into `main`

**Comment by tmwatchanan** [comment] 2024-02-24 21:35
I've tested it and it's working quite well, at least for three-digit numbers and below. I think it's good to go! Thanks again, @dedukun.

**Comment by dedukun** [comment] 2024-02-24 21:49
I've merged it. I might change it a bit in the future to work better with 1000+ files and I might add a flag to disable this offset, but for now I think that it's fine like this.

I'm closing this issue, thanks for the suggestion and testing the PR.

**Closed by dedukun** 2024-02-24 21:49 UTC

**Comment by ProfiGMan** [comment] 2024-07-14 00:34
Same problem again. Yazi says the File global variable has been removed

**Comment by dedukun** [comment] 2024-07-14 17:27
Hey, yes I noticed now, upstream  [changed the UI extension](https://github.com/sxyazi/yazi/pull/1257)  code, so what we have now doesn't work. I'll try to fix it as soon as possible

**Comment by dedukun** [comment] 2024-07-14 18:51
@ProfiGMan should be fixed in HEAD.

**Comment by ProfiGMan** [comment] 2024-07-15 12:40
Works just as intended! Thanks a lot

**Comment by khaitranhq** [comment] 2024-10-23 15:56
Same problem. I tried all values of `show_numbers` and only `none` can show files/directories again

**Comment by dedukun** [comment] 2024-10-25 20:42
Hey @khaitranhq, what version of Yazi are you using?

A couple of weeks back, upstream changed an API that we use in the plugin and I added supported to it in 026fb16, if you are using release 0.3.3 it might be that you need to use a previous commit, I created branch https://github.com/dedukun/relative-motions.yazi/tree/0.3.3 that you can use to test it.

If that doesn't fixes your issue, please create a new issue so that we can look further into it.
